# Generated by Django 5.2.4 on 2025-07-29 00:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Adresse_livraison', models.TextField()),
                ('Date_heure_livraison', models.DateTimeField()),
                ('Statut', models.CharField(choices=[('en_attente', 'En attente'), ('preparation', 'En préparation'), ('livraison', 'En livraison'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
