# Generated by Django 5.2.4 on 2025-07-29 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
        ('nourritures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='IdFood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='nourritures.nourriture'),
        ),
    ]
