# Generated by Django 5.2.4 on 2025-07-29 00:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
                ('Photo_de_couverture', models.ImageField(blank=True, null=True, upload_to='etablissements/couvertures/')),
                ('Description', models.TextField(blank=True)),
                ('Horaire_ouverture', models.CharField(blank=True, max_length=1000)),
                ('Emplacement', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
