# Generated by Django 5.2.4 on 2025-07-29 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraireOuverture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.PositiveSmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('ouverture_matin', models.TimeField(blank=True, null=True)),
                ('fermeture_matin', models.TimeField(blank=True, null=True)),
                ('ouverture_soir', models.TimeField(blank=True, null=True)),
                ('fermeture_soir', models.TimeField(blank=True, null=True)),
                ('est_ferme', models.BooleanField(default=False)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='etablissements.etablissement')),
            ],
            options={
                'ordering': ['jour'],
                'unique_together': {('etablissement', 'jour')},
            },
        ),
    ]
