# Generated by Django 5.2.4 on 2025-08-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissements', '0003_horaireouverture'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='Active',
            field=models.BooleanField(default=True),
        ),
    ]
