# Generated by Django 5.2.4 on 2025-07-29 00:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etablissements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nourriture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
                ('Prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='foods/photos/')),
                ('Temps_preparation', models.PositiveIntegerField(help_text='Temps en minutes')),
                ('Description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('IdEtablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nourritures', to='etablissements.etablissement')),
            ],
        ),
    ]
