# Generated by Django 5.2.4 on 2025-08-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nourritures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nourriture',
            name='Note',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='nourriture',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
