# Generated by Django 5.2.4 on 2025-08-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nourritures', '0002_nourriture_note_nourriture_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='nourriture',
            name='nb_avis',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
