# Generated by Django 5.2.4 on 2025-08-03 03:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nourritures', '0003_nourriture_nb_avis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nourriture',
            options={'ordering': ['-disponible', 'Nom'], 'verbose_name': 'Nourriture', 'verbose_name_plural': 'Nourritures'},
        ),
        migrations.AlterField(
            model_name='nourriture',
            name='Note',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='nourriture',
            name='Temps_preparation',
            field=models.PositiveIntegerField(help_text='Temps en minutes', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
